version: "3"
services:
  rabbitmqsrv:
    image: rabbitmq
    ports: 
      - "5672:5672"
  tserver:
    build: ./tserver
    ports:
      - "9001:9001"
    links:
      - rabbitmqsrv
  tclient:
    build: ./tclient
    ports:
      - "8000:8000"
    links:
      - tserver
